// Code generated by goctl. DO NOT EDIT.
package types

type AdminUser struct {
	AdminUid  string `json:"admin_uid"`
	AuditType int64  `json:"audit_type"`
	OpTime    int64  `json:"op_time"`
	OpDip     string `json:"op_dip"`
	OpDname   string `json:"op_dname"`
}

type CreateAdminUserRequest struct {
	AdminUser
}

type CreateAdminUserResponse struct {
	Id int64 `json:"id"`
}

type CreateOpLogRequest struct {
	OpLog
}

type CreateOpLogResponse struct {
	Id int64 `json:"id"`
}

type EmptyReq struct {
}

type EmptyResp struct {
	RespBase
}

type GetAdminUserResponse struct {
	RespBase
	Data []AdminUser `json:"data"`
}

type GetOpLogResponse struct {
	RespBase
	Data []OpLog `json:"data"`
}

type OpLog struct {
	AdminUid  string `json:"admin_uid"`
	AuditType int64  `json:"audit_type"`
	OpTime    int64  `json:"op_time"`
	OpDip     string `json:"op_dip"`
	OpDname   string `json:"op_dname"`
}

type RespBase struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
