// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	adminuser "x-HanYun/internal/handler/adminuser"
	oplog "x-HanYun/internal/handler/oplog"
	"x-HanYun/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: adminuser.CreateAdminUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/api/adminser"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: oplog.CreateOpLogHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/api/oplog"),
	)
}
