// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbOpLogFieldNames          = builder.RawFieldNames(&TbOpLog{})
	tbOpLogRows                = strings.Join(tbOpLogFieldNames, ",")
	tbOpLogRowsExpectAutoSet   = strings.Join(stringx.Remove(tbOpLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tbOpLogRowsWithPlaceHolder = strings.Join(stringx.Remove(tbOpLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tbOpLogModel interface {
		Insert(ctx context.Context, data *TbOpLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TbOpLog, error)
		Update(ctx context.Context, data *TbOpLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTbOpLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TbOpLog struct {
		Id       int64  `db:"id"`        // 唯一标识
		UserId   string `db:"user_id"`   // 操作用户ID
		OpTime   int64  `db:"op_time"`   // 操作时间
		OpDip    string `db:"op_dip"`    // 操作设备IP
		OpDname  string `db:"op_dname"`  // 操作设备名称
		OpDetail string `db:"op_detail"` // 操作详情
		Ctime    int64  `db:"ctime"`     // 创建时间
		Mtime    int64  `db:"mtime"`     // 更新时间
	}
)

func newTbOpLogModel(conn sqlx.SqlConn) *defaultTbOpLogModel {
	return &defaultTbOpLogModel{
		conn:  conn,
		table: "`tb_op_log`",
	}
}

func (m *defaultTbOpLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTbOpLogModel) FindOne(ctx context.Context, id int64) (*TbOpLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tbOpLogRows, m.table)
	var resp TbOpLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbOpLogModel) Insert(ctx context.Context, data *TbOpLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, tbOpLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.OpTime, data.OpDip, data.OpDname, data.OpDetail, data.Ctime, data.Mtime)
	return ret, err
}

func (m *defaultTbOpLogModel) Update(ctx context.Context, data *TbOpLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tbOpLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.OpTime, data.OpDip, data.OpDname, data.OpDetail, data.Ctime, data.Mtime, data.Id)
	return err
}

func (m *defaultTbOpLogModel) tableName() string {
	return m.table
}
